### ISSUE TITLE
output of variables in matching rules can contain problematic characters

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusStream#33]
```
Kapitalerhoehung [48..55, 0|357 .. 0|426]: alt_wert [54..55, 0|413 .. 0|426] '19'200'000.00' neu_wert [51
```
The single quote should be escaped.
The same may apply to non-printables (ok, granted, who select newlines?).

**Comment by andreasbaumann** [comment]
I think it's sufficient to add the ' case in encodeOutput of strusPatternMatcher.cpp in the utilities.
Also such a function is a good candidate for a being a generic string escape function in strusBase.

**Comment by andreasbaumann** [comment]
```
diff --git a/src/strusPatternMatcher/strusPatternMatcher.cpp b/src/strusPatternMatcher/strusPatternMatcher.cpp
index 5415e8a..ffa3f01 100644
--- a/src/strusPatternMatcher/strusPatternMatcher.cpp
+++ b/src/strusPatternMatcher/strusPatternMatcher.cpp
@@ -475,6 +475,11 @@ public:
                        {
                                rt.push_back( ' ');
                        }
+                       else if ((unsigned char)ptr[si] == '\'')
+                       {
+                               rt.push_back( '\\' );
+                               rt.push_back( '\'' );
+                       }
                        else
                        {
                                rt.push_back( ptr[si]);
```
works for me.

**Comment by andreasbaumann** [comment]
Mapping non-printables to space? Maybe better \021 etc.?

**Comment by patrickfrey** [comment]
The pattern matcher program output of strusPatternMatcher can be defined by a format string.
The default is
"{name} [{ordpos}..{ordend}, {startseg}\\|{startpos} .. {endseg}\\|{endpos}]:{value}| {name} [{ordpos}..{ordend}, {startseg}\\|{startpos} .. {endseg}\\|{endpos}] '{value}'|"

Besides {startseg} and {startpos} you can also use {abspos} which is {startseg}+{startpos}.
Control character in {value} are substituted by spaces. 

If you have quotes in the output, you can use another delimiter for the result.
Another value substitute instead of {value} implementing a certain encoding is also thinkable.

**Comment by patrickfrey** [comment]
Non-printables are mapped to space for a while now. Closing the issue.
